### PR TITLE
Makes Hugo dependency explicit

### PR DESCRIPTION
**Pull request by ArquintL**
This PR integrates the Hugo dependency into NPM since we use NPM anyway. This makes it explicit on which Hugo version we depend.
Note that I have not tested the script to run Hugo for Windows

### CODE REVIEW

**Comment by felixlinker** [comment]
So I just did it the other way around and removed all npm dependencies, just linking to the templates description 😄 I think I like your approach more because it should lead to easier reproducible builds. Do you happen to know whether npm also installs go? You could check in the `node_modules` folder quickly.

**Comment by ArquintL** [comment]
Why do we need Go in the first place? I'm using a pre-built Hugo binary

**Comment by ArquintL** [comment]
Getting rid of NPM sounds good too. It's a bit annoying that we need platform specific scripts because we have to manipulate the PATH

**Comment by felixlinker** [comment]
Then let's get rid of the platform-dependent scripts! Make repo simpler as well.

**Comment by felixlinker** [comment]
FYI: On Mac you just need to run `brew install sass/sass/sass` and it should work.

**Comment by ArquintL** [comment]
Wait but this is now way worse! Instead of having explicit and version-controlled dependencies, we implicitly depend on Hugo & some sass compiler! I thought you found a way how we do not need the sass dependency

**Comment by felixlinker** [comment]
But in all honesty, I think npm introduces more problems than it solves. You modified the mac script for your purposes (which makes sense), but it now will have stopped working for me. Also, the `hugo-installer` dependency does not fix a hugo version, but will always install the latest. (It's an installer, not hugo itself.) If we could run everything from within npm (via `npx`) that would be nice, but that doesn't work because hugo will still be installed for the user.

I think linking to the theme's documentation is much more future-proof.

**Comment by ArquintL** [comment]
> But in all honesty, I think npm introduces more problems than it solves. You modified the mac script for your purposes (which makes sense), but it now will have stopped working for me. Also, the hugo-installer dependency does not fix a hugo version, but will always install the latest. (It's an installer, not hugo itself.) If we could run everything from within npm (via npx) that would be nice, but that doesn't work because hugo will still be installed for the user.
> I think linking to the theme's documentation is much more future-proof.

`package.json` not only specifies the `hugo-intaller` but also `hugo` version (`4.0.1` and `0.121.2`, resp.). `npm install` will download the `hugo` binary to `bin/hugo/hugo`. I've adapted the scripts to use that binary. Since your mac script only works for Apple Silicon, there are now two separate scripts `mac-hugo.sh` and `mac-arm-hugo.sh`. In retrospect, I shouldn't have picked the names in this way that `x86` became the default for macOS...

**Comment by felixlinker** [comment]
@ArquintL Thanks for pointing that out! I added an npm script so that we don't need the OS-dependent scripts anymore. Documented in README! And thanks for improving dependency management.

**Comment by ArquintL** [comment]
I've just been super-confused while playing around that we do not seem to need an (external) sass dependency. It seems that Hugo (in its extended version) comes with sass built in

**Comment by felixlinker** [comment]
For the `npm run` script you also don't need to add sass on the path because all the packages are loaded as dependencies.

Or are you certain that we could drop sass from the dependencies?

**Comment by felixlinker** [comment]
Ah, saw your commit. Great! Thanks!

**Pull request merged**
